"""
Abstract base class for all trading strategies.

Every strategy is a testable hypothesis with:
- A theoretical basis (WHY it should work)
- Entry conditions (WHEN to enter)
- Exit conditions (WHEN to exit)
- Stop-loss logic (WHEN the thesis is broken)
- A confidence threshold (HOW SURE we need to be)

Strategies are STATELESS — they take features and return signals.
State (open positions, P&L) is managed by the execution layer.
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import Any


@dataclass
class Signal:
    """A trading signal generated by a strategy."""
    direction: str          # 'long', 'short', or 'hold'
    confidence: float       # [0, 1]
    strategy: str           # Strategy name
    hypothesis_id: str      # Hypothesis ID from YAML
    stop_loss: float        # Price level for stop-loss
    take_profit: float      # Price level for take-profit
    explanation: str        # Human-readable WHY this signal was generated
    features_snapshot: dict # Feature values at signal time


class BaseStrategy(ABC):
    """
    Abstract base class for all trading strategies.

    Subclasses implement check_entry() and check_exit() using
    the feature values available at a given point in time.
    """

    def __init__(self, config: dict) -> None:
        """
        Args:
            config: Strategy configuration from hypotheses.yaml.
                   Contains: id, name, theory_basis, entry_conditions,
                   exit_conditions, stop_loss, take_profit, etc.
        """
        self.config = config
        self.hypothesis_id: str = config.get("id", "UNKNOWN")
        self.name: str = config.get("name", "Unknown Strategy")
        self.theory_basis: str = config.get("theory_basis", "")
        self.confidence_threshold: float = config.get("confidence_threshold", 0.65)
        self.max_positions: int = config.get("max_positions", 2)
        self.time_horizon: str = config.get("time_horizon", "1-5 days")

        # Stop-loss configuration
        self.stop_config: dict = config.get("stop_loss", {})
        # Take-profit configuration
        self.tp_config: dict = config.get("take_profit", {})

    @abstractmethod
    def check_entry(self, features: dict[str, float], current_price: float) -> Signal | None:
        """
        Check if entry conditions are met.

        Args:
            features: Current feature values (from FeatureBuilder).
            current_price: Current market price.

        Returns:
            Signal if conditions met, None otherwise.
        """
        ...

    @abstractmethod
    def check_exit(
        self,
        features: dict[str, float],
        current_price: float,
        entry_price: float,
        direction: str,
        holding_days: int,
    ) -> tuple[bool, str]:
        """
        Check if exit conditions are met for an open position.

        Args:
            features: Current feature values.
            current_price: Current market price.
            entry_price: Price at which position was entered.
            direction: 'long' or 'short'.
            holding_days: Number of days position has been open.

        Returns:
            Tuple of (should_exit, reason).
        """
        ...

    def calculate_stop_loss(self, current_price: float, atr: float, direction: str) -> float:
        """
        Calculate stop-loss price based on strategy configuration.

        Args:
            current_price: Current market price.
            atr: Current ATR value.
            direction: 'long' or 'short'.

        Returns:
            Stop-loss price level.
        """
        method = self.stop_config.get("method", "atr")
        multiplier = self.stop_config.get("multiplier", 2.0)

        if method == "atr":
            distance = atr * multiplier
            if direction == "long":
                return current_price - distance
            else:
                return current_price + distance
        elif method == "percentage":
            pct = self.stop_config.get("value", 0.5) / 100.0
            if direction == "long":
                return current_price * (1 - pct)
            else:
                return current_price * (1 + pct)
        elif method == "keltner_midline":
            # Caller must provide keltner_mid in features
            return current_price  # Placeholder — overridden in strategy

        return current_price  # Fallback

    def calculate_take_profit(self, current_price: float, atr: float, direction: str) -> float:
        """
        Calculate take-profit price based on strategy configuration.

        Args:
            current_price: Current market price.
            atr: Current ATR value.
            direction: 'long' or 'short'.

        Returns:
            Take-profit price level.
        """
        method = self.tp_config.get("method", "atr")
        multiplier = self.tp_config.get("multiplier", 3.0)

        if method == "atr":
            distance = atr * multiplier
            if direction == "long":
                return current_price + distance
            else:
                return current_price - distance
        elif method == "trailing":
            # Trailing stops are managed by the execution layer
            trail_atr = self.tp_config.get("trail_atr", 1.5)
            distance = atr * trail_atr
            if direction == "long":
                return current_price + distance
            else:
                return current_price - distance

        return current_price  # Fallback

    def _build_signal(
        self,
        direction: str,
        confidence: float,
        current_price: float,
        atr: float,
        features: dict[str, float],
        explanation: str,
    ) -> Signal:
        """Helper to construct a Signal with stop/TP calculations."""
        return Signal(
            direction=direction,
            confidence=confidence,
            strategy=self.name,
            hypothesis_id=self.hypothesis_id,
            stop_loss=self.calculate_stop_loss(current_price, atr, direction),
            take_profit=self.calculate_take_profit(current_price, atr, direction),
            explanation=explanation,
            features_snapshot=features,
        )
